dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  intl: ^0.19.0
  
  # Firebase
  firebase_core: ^2.28.0
  firebase_auth: ^4.16.1
  cloud_firestore: ^4.16.1
  
  # Google Sign In with specific version for web compatibility
  google_sign_in: ^6.1.6
  
  # Add this for better Google Sign-In on web
  google_sign_in_web: ^0.12.7